-- MySQL Script generated by MySQL Workbench
-- Fri Nov  1 09:58:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Proveïdors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Proveïdors` (
  `id_Proveïdors` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `carrer` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `pis` VARCHAR(10) NULL,
  `porta` VARCHAR(5) NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `país` VARCHAR(20) NOT NULL,
  `teléfon` NCHAR(10) NOT NULL,
  `fax` NCHAR(10) NULL,
  `nif` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_Proveïdors`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ulleres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ulleres` (
  `id_Ulleres` INT NOT NULL,
  `Marca` VARCHAR(45) NOT NULL,
  `graduació_lent_dreta` DECIMAL NOT NULL,
  `graduació_lent_esquerra` DECIMAL NOT NULL,
  `tipus_muntura` VARCHAR(45) NOT NULL,
  `color_lent_Esquerra` VARCHAR(10) NOT NULL,
  `color_lent_Dreta` VARCHAR(10) NOT NULL,
  `preu` DOUBLE NOT NULL,
  `proveïdors_ID_Proveïdors` INT NULL,
  PRIMARY KEY (`id_Ulleres`),
  INDEX `fkUlleres_Proveïdors_idx` (`proveïdors_ID_Proveïdors` ASC) VISIBLE,
  CONSTRAINT `fkUlleres_Proveïdors`
    FOREIGN KEY (`proveïdors_ID_Proveïdors`)
    REFERENCES `mydb`.`Proveïdors` (`id_Proveïdors`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `id_Clients` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `cp` INT NOT NULL,
  `teléfon` NCHAR(10) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_Alta` DATETIME NOT NULL,
  `Recomanat_per` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Clients`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ventas` (
  `id_Ventas` INT NOT NULL,
  `Clients_ID_Clients` INT NOT NULL,
  `Ulleres_id_Ulleres` INT NOT NULL,
  `Ulleres_preu` DOUBLE NOT NULL,
  `data_venta` DATETIME NOT NULL,
  `venedor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Ventas`),
  INDEX `fk_Ventas_Clients_idx` (`Clients_ID_Clients` ASC) VISIBLE,
  INDEX `fk_Ventas_Ulleres_idx` (`Ulleres_id_Ulleres` ASC) VISIBLE,
  CONSTRAINT `fk_Ventas_Clients`
    FOREIGN KEY (`Clients_ID_Clients`)
    REFERENCES `mydb`.`Clients` (`id_Clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_Ulleres`
    FOREIGN KEY (`Ulleres_id_Ulleres`)
    REFERENCES `mydb`.`Ulleres` (`id_Ulleres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
